import datetime
DATE = datetime.date.today().strftime("%Y%m%d")


# Setup config and functions ===================================================
# Use docker image
# container: "docker://f06b22037/bioinfobase:latest"

# Load configuration file (as config)
configfile: "./configs/config.json"

# Include rules
#include: "rules/SS_MQD.smk"

#LCM data is too huge
#include: "rules/SS_MQD_noss.smk"
###
include: "rules/SS_single_cell.smk"
#include: "rules/SS_ortholog.smk"
#include: "rules/SS_ortholog_Cla.smk"
#
#include: "rules/MS_single_cell.smk"
# different parameters
include: "rules/MS_single_cell_anchor.smk"


#include: "rules/MS_phylogeny.smk"


# Define rules for execution ===================================================



rule scRNATung_snRNABio2:
    input:
        expand(
            "results/Single_species_analysis/cellranger_reanalysis_{sample}",
            sample = [
                "TenX_Ptr",
                "TenX_NucXyBio2"          
            ]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_{level}/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            level = [
                "sample"
            ],
            multisample = [
                "scRNATung_snRNABio2"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5] # [5, 10]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_species/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            multisample = [
                "scRNATung_snRNABio2"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5], # [5, 10]
        )



rule scRNATung_snRNABio3:
    input:
        expand(
            "results/Single_species_analysis/cellranger_reanalysis_{sample}",
            sample = [
                "TenX_Ptr",
                "TenX_NucXyBio3"          
            ]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_{level}/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            level = [
                "sample"
            ],
            multisample = [
                "scRNATung_snRNABio3"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5] # [5, 10]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_species/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            multisample = [
                "scRNATung_snRNABio3"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5], # [5, 10]
        )


rule snRNA_Bio2_Bio3:
    input:
        expand(
            "results/Single_species_analysis/cellranger_reanalysis_{sample}",
            sample = [
                "TenX_NucXyBio2",
                "TenX_NucXyBio3"          
            ]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_{level}/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            level = [
                "sample"
            ],
            multisample = [
                "snRNA_Bio2_Bio3"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5] # [5, 10]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_species/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            multisample = [
                "snRNA_Bio2_Bio3"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5], # [5, 10]
        )






rule scRNATung_ProtosnRNABio1:
    input:
        expand(
            "results/Single_species_analysis/cellranger_reanalysis_{sample}",
            sample = [
                "TenX_Ptr",
                "TenX_NucXyProtoBio1"          
            ]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_{level}/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            level = [
                "sample"
            ],
            multisample = [
                "scRNATung_ProtosnRNABio1"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5] # [5, 10]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_species/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            multisample = [
                "scRNATung_ProtosnRNABio1"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5], # [5, 10]
        )



rule scRNATung_ProtosnRNABio2:
    input:
        expand(
            "results/Single_species_analysis/cellranger_reanalysis_{sample}",
            sample = [
                "TenX_Ptr",
                "TenX_NucXyProtoBio2"          
            ]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_{level}/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            level = [
                "sample"
            ],
            multisample = [
                "scRNATung_ProtosnRNABio2"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5] # [5, 10]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_species/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            multisample = [
                "scRNATung_ProtosnRNABio2"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5], # [5, 10]
        )




rule snRNABio2_ProtosnRNABio1:
    input:
        expand(
            "results/Single_species_analysis/cellranger_reanalysis_{sample}",
            sample = [
                "TenX_NucXyBio2",
                "TenX_NucXyProtoBio1"          
            ]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_{level}/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            level = [
                "sample"
            ],
            multisample = [
                "snRNABio2_ProtosnRNABio1"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5] # [5, 10]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_species/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            multisample = [
                "snRNABio2_ProtosnRNABio1"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5], # [5, 10]
        )





rule snRNABio3_ProtosnRNABio2:
    input:
        expand(
            "results/Single_species_analysis/cellranger_reanalysis_{sample}",
            sample = [
                "TenX_NucXyBio3",
                "TenX_NucXyProtoBio2"          
            ]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_{level}/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            level = [
                "sample"
            ],
            multisample = [
                "snRNABio3_ProtosnRNABio2"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5] # [5, 10]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_species/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            multisample = [
                "snRNABio3_ProtosnRNABio2"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5], # [5, 10]
        )




rule snRNABio3_ProtosnRNABio1:
    input:
        expand(
            "results/Single_species_analysis/cellranger_reanalysis_{sample}",
            sample = [
                "TenX_NucXyBio3",
                "TenX_NucXyProtoBio1"          
            ]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_{level}/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            level = [
                "sample"
            ],
            multisample = [
                "snRNABio3_ProtosnRNABio1"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5] # [5, 10]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_species/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            multisample = [
                "snRNABio3_ProtosnRNABio1"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5], # [5, 10]
        )





rule snRNABio2_ProtosnRNABio2:
    input:
        expand(
            "results/Single_species_analysis/cellranger_reanalysis_{sample}",
            sample = [
                "TenX_NucXyBio2",
                "TenX_NucXyProtoBio2"          
            ]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_{level}/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            level = [
                "sample"
            ],
            multisample = [
                "snRNABio2_ProtosnRNABio2"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5] # [5, 10]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_species/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            multisample = [
                "snRNABio2_ProtosnRNABio2"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5], # [5, 10]
        )

rule ProtosnRNABio1_ProtosnRNABio2:
    input:
        expand(
            "results/Single_species_analysis/cellranger_reanalysis_{sample}",
            sample = [
                "TenX_NucXyProtoBio1",
                "TenX_NucXyProtoBio2"          
            ]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_{level}/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            level = [
                "sample"
            ],
            multisample = [
                "ProtosnRNABio1_ProtosnRNABio2"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5] # [5, 10]
        ),
        expand(
            "results/Multi_species_analysis/UMAP_by_species/integration_{multisample}_an_{anchor}_ft_{filters}_kan_{k_anchor}_seed_{seed_use}_md_{min_dist}_nn_{n_neighbors}",
            multisample = [
                "ProtosnRNABio1_ProtosnRNABio2"
            ],
            seed_use = [42], # [42, 12345, 231, 938, 29, 1, 948, 943, 377, 412, 9889, 20, 16, 21, 33, 23]
            min_dist = [0.3], # [0.001, 0.1, 0.2, 0.3, 0.4, 0.5],
            n_neighbors = [30], # [5, 10, 20, 30, 40 ,50],
            anchor = [2000], # [1000, 1500, 2000, 3000]
            filters = [200], # [200, 500, 700, 1000]
            k_anchor = [5], # [5, 10]
        )


